name: dev-build

on:
    push:
        branches: [ dev ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy app
              uses: appleboy/ssh-action@v0.1.4
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USER }}
                password: ${{ secrets.SERVER_PASS }}
                script: |
                    source ~/.bashrc >> /dev/null 2>&1
                    cd ${{ secrets.DEV_PROJECT_PATH }} >> /dev/null 2>&1
                    git pull >> /dev/null 2>&1
                    npm ci >> /dev/null 2>&1
                    npm run build >> /dev/null 2>&1
                    pm2 reload ecosystem.config.js >> /dev/null 2>&1
                    pm2 save >> /dev/null 2>&1
