name: CI

on:
    push:
        branches: [ dev ]
    pull_request:
        branches: [ dev ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Deploy app
              uses: appleboy/ssh-action@v0.1.4
              with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.REMOTE_USER }}
                key: ${{ secrets.SERVER_SSH_KEY }}
                script: |
                    source ~/.bashrc
                    cd ${{ secrets.REMOTE_TARGET }}
                    git pull
                    yarn install
                    yarn build:prod
