name: CI

on:
    push:
        branches: [ dev ]
    pull_request:
        branches: [ dev ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy app
              uses: appleboy/ssh-action@v0.1.4
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USER }}
                password: ${{ secrets.SERVER_PASS }}
                script: |
                    source ~/.bashrc >> /dev/null 2>&1
                    cd ${{ secrets.PROJECT_PATH }} >> /dev/null 2>&1
                    git pull >> /dev/null 2>&1
                    pm2 stop ecosystem.config.js >> /dev/null 2>&1
                    rm -rf ./node_modules >> /dev/null 2>&1
                    npm ci >> /dev/null 2>&1
                    npm run build:prod >> /dev/null 2>&1
                    pm2 start ecosystem.config.js >> /dev/null 2>&1
