name: Restart

on:
  workflow_dispatch:

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: restart
  cancel-in-progress: false

jobs:
  restart-dev:
    name: Restart Job
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script:
            pm2 restart ${{ github.ref_name == 'dev' && 'ttg-club-telegram-dev'
            || 'ttg-club-telegram' }}
